package com.example.pentapal.ui.repositories

import com.example.pentapal.ui.models.Skill
import com.google.firebase.firestore.DocumentReference
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.firestore.ktx.toObjects
import com.google.firebase.ktx.Firebase
import kotlinx.coroutines.tasks.await

object SkillsRepository {
    private val skillsCache = mutableListOf<Skill>()
    private var cacheInitialized = false
    private var skillBuffer = Skill()

    suspend fun getSkills(): List<Skill> {
        if (!cacheInitialized) {
            cacheInitialized = true
            val snapshot = Firebase.firestore.collection("skills").get().await()
            skillsCache.addAll(snapshot.toObjects())
        }
        return skillsCache
    }

    suspend fun loadSkills() {
        for (skill in skillsAdd){
            val doc = Firebase.firestore.collection("skills").document()
            val skill = Skill(
                id = doc.id,
                name = skill.name,
                set = skill.set,
                type = skill.type,
                level = skill.level,
                focusMode = skill.focusMode,
                slots = skill.slots,
                traits = skill.traits,
                description = skill.description,
            )
            doc.set(skill).await()
        }
    }

    fun setBuffer(skill: Skill){
        skillBuffer = skill
    }

    fun getBuffer(): Skill {
        val skill = skillBuffer
        return skill
    }

    fun resetBuffer(){
        skillBuffer = Skill()
    }

    private val skillsAdd = listOf<Skill>(
//        Skill(
//            name = "Elemental Dart",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "You fire a magical dart of a type of your choice: Ice, Fire, or Lightning, at a target within 30 ft/6 hexes.  If the attack hits, you deal 2d5 + half Magic damage.  If you choose Ice, the target is Chilled for 2 turns. If you choose Fire, the target is Burned for 2 turns.  If you choose Lightning, the target is Shocked.",
//        ),
//        Skill(
//            name = "Infernal Teleport",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Movement","Attack"),
//            traits = listOf("Devil Worship"),
//            description = "You vanish in a puff of smoke, and reappear within 20 ft/4 hexes in a burst of flames, dealing 1d5 damage to all targets within 5 ft/1 hex of your new location without rolling to hit.",
//        ),
//        Skill(
//            name = "Protective Aura",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Defense","Support"),
//            traits = listOf(""),
//            description = "An orb of blessed power surrounds you or an ally within 15 ft/3 hexes. The aura absorbs damage, and will stay until it has absorbed 1d5 + half Magic or more damage.  While the aura is active, the target heals 1d5 damage at the start of their turn, and rolls to hit against them must be above 3/10 (overridden by higher hit resist chances).",
//        ),
//        Skill(
//            name = "Energy Absorption",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Support"),
//            traits = listOf(""),
//            description = "The spiritual energy around you heals you for 1d5 health at the start of each of your turns.",
//        ),
//        Skill(
//            name = "Chthonic Luck",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "The blessing of your Elder Gods rests upon you. Once per combat, you may force an attack roll that would hit you to be rerolled.",
//        ),
//        Skill(
//            name = "Bludgeon",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = true,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "You swing a firm improvised weapon into the skull of an enemy, dealing 2d5 + half Power damage if you hit and making the target Dizzy.\n" +
//                    "Focus Mode/Cost: 3 Turn Cooldown\n" +
//                    "You make the same attack as the standard skill, but the target is Staggered instead of Dizzy.\n",
//        ),
//        Skill(
//            name = "Cheap Shot",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Utility"),
//            traits = listOf(""),
//            description = "You take a swing at a target within 5 ft/1 hex, dealing 1d5 + half Power damage if it hits.  If the target is affected by a status effect, you deal 2d5 + Power damage instead.",
//        ),
//        Skill(
//            name = "Ley Lines",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Support"),
//            traits = listOf(""),
//            description = "When you take your free movement, you leave magical ley lines on the ground behind you.  These lines last until the start of your next turn.  Allies standing on a ley line deal +1 damage on all damage instances, and take 1 reduced damage from all sources.  If the lines connect into a polygon with empty hexes inside, this effect is doubled for those standing inside the lines.",
//        ),
//        Skill(
//            name = "Exorcizing Fist",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf("Spirit Medium"),
//            description = "Commanding spiritual power, you separate a target’s soul from their body for a moment with a punch.  If your attack hits a target within 5 ft/1 hex, you deal 2d5 + half Power damage, and the target is Staggered until the end of their next turn.",
//        ),
//        Skill(
//            name = "Spectral Body",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf("Spirit Medium"),
//            description = "Your body becomes almost incorporeal, fading partially into the spirit world.  Until the end of your next turn, rolls to hit against you must be higher than 5/10. You may move through enemies and walls.",
//        ),
//        Skill(
//            name = "Muscle Mass",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "All instances of damage you take are reduced by 2.",
//        ),
//        Skill(
//            name = "Toxic Bubbles",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf("Plague Bearer"),
//            description = "You create a torrent of poisonous bubbles around a target within 15 ft/3 hexes. This target is applied with 2d5 Poison stacks without rolling to hit, and any creature within 5 ft/1 hex of the target is applied with 2 stacks of Poison as well.",
//        ),
//        Skill(
//            name = "Blood Poison",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf("Plague Bearer"),
//            description = "When an enemy hits you with an attack from within 5 ft/1 hex of you, you apply 1d5 Poison stacks to them.",
//        ),
//        Skill(
//            name = "Vengeful Spirit",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 2,
//            focusMode = true,
//            slots = listOf("Utility"),
//            traits = listOf("Spirit Medium"),
//            description = "When you kill an enemy on your turn, you briefly retain their spirit, and may command it to fly to and attack an enemy within 30 ft/6 hexes of the dead enemy, making that enemy’s Attack action against the target (if possible).\n" +
//                    "Focus Mode/Cost: 1 Charge\n" +
//                    "Max Charges: 3\n" +
//                    "When you kill an enemy, you briefly retain their spirit, and may take an entire turn controlling that enemy.\n",
//        ),
//        Skill(
//            name = "Devil Form",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Movement","Defense"),
//            traits = listOf("Devil Worship"),
//            description = "Your body takes a more demonic form, sprouting wings and tougher, leathery skin for 2 turns.  While in this form, your free movement is increased by 15 ft/3 hexes and you may fly over enemies and short obstacles during your free movement as well, and damage less than your Vigor is negated.  ",
//        ),
//        Skill(
//            name = "Spectral Dash",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Movement"),
//            traits = listOf(""),
//            description = "Transforming into a semi-smoky shade, you dash quickly up to 20 ft/4 hexes + your maximum free movement distance.  You may move through enemies and walls.",
//        ),
//        Skill(
//            name = "Chthonic Cardio",
//            set = "Calamitous Cult",
//            type = "Both",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Movement","Support"),
//            traits = listOf(""),
//            description = "Passive\n" +
//                    "The ancient energy of the ground beneath your feet invigorates you, and you heal 1 health for every 5 ft/1 hex traveled during your free movement.\n" +
//                    "Active\n" +
//                    "You or an ally within 30 ft/6 hexes may immediately move up to 15 ft/3 hexes, and they heal 1d5 health for every 5 ft/1 hex traveled during this movement.\n",
//        ),
//        Skill(
//            name = "Faerie Summons",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Utility"),
//            traits = listOf("Friend of the Fae"),
//            description = "You conjure a small Faerie, cajoled into aiding your endeavors.  The small being will perform tasks for you until it grows bored of doing so.  The first task it will always fulfill, and for successive tasks you must roll a d5.  If you roll a 1 or 2, the faerie departs.  The tasks it may perform are: Heal a target for 1d10 or your Magic, Damage a target for 2d5 or your Magic, Apply Dizzy to a target, Remove 1 status from a target, or Move a target up to 10 ft/2 hexes.",
//        ),
//        Skill(
//            name = "Three-Edge Dagger",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "You drive a wicked triple-edged triangular dagger into a target within 5 ft/1 hex, dealing 3d5 + half Power if you hit, and apply Bleed equal to your Power for 3 turns.",
//        ),
//        Skill(
//            name = "Shadow Brotherhood",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "Drawing your cultist cloak tight, shadow copies of yourself seems to surround you.  For 2 turns, rolls to hit against you must be higher than 3/5. ",
//        ),
//        Skill(
//            name = "Ritual Sacrifice",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = true,
//            slots = listOf("Utility"),
//            traits = listOf(""),
//            description = "You plunge a ritual dagger into a target within 5 ft/1 hex, dealing 3d5 damage if it hits.  If this attack kills the target, you and all allies within 30 ft/6 hexes of the target are healed 3d5 health, and negate damage less than your Magic for 1 turn.\n" +
//                    "Focus Mode/Cost: 1 Focus\n" +
//                    "Your attack with the ritual dagger does 3d5 damage without rolling to hit, and if the target is below 20% health, it is automatically killed.  If it is killed by this attack, you and all allies within 30 ft/3 hexes are healed 3d5 health + Magic, and negate damage less than your Magic for 2 turns.\n",
//        ),
//        Skill(
//            name = "Fae Grudge",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Movement","Attack","Defense","Support"),
//            traits = listOf("Friend of the Fae"),
//            description = "A powerful fae holds a powerful grudge against you.  You take +1 damage from all instances of damage.  When you drop to 0 hp while this skill is equipped, it is permanently removed, but the Trait remains on your character and cannot be removed.",
//        ),
//        Skill(
//            name = "Horoscope",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Movement","Attack","Defense","Support"),
//            traits = listOf(""),
//            description = "While this skill is equipped, you are granted power based on the destiny given to you by the stars. Aquarius: Magic +2, Pisces: Healing Given/Received +1d5, Aries: Power +2, Taurus: Vigor +2, Gemini: Odd Stats +1 (only applies when first equipped, please note which stats were increased in case this skill is removed later), Cancer: -1 Damage Taken, Leo: +2 Speed, Virgo: +2 Focus, Libra: +3 to lowest Stat(note which stat in case skill is unequipped), Scorpio: +2 to Damage  Dealt within 5 ft/1 hex, Sagittarius: +2 to Damage Dealt further than 5 ft/1 hex, Capricorn: +1 to Stat of your choice.",
//        ),
//        Skill(
//            name = "Bog and Mire",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Attack","Support"),
//            traits = listOf("Plague Bearer"),
//            description = "A toxic swamp spreads from under your feet in a circle, with a radius equal to 5 ft/1 hex for each point in half your Speed.  Enemies that start their turn in or enter this swamp are applied 3 stacks of Poison, and enemy Poison stacks cannot be reduced or cleansed while they stand in the bog.  The swamp lasts for 3 turns, and can be recast to shift location or refresh duration.",
//        ),
//        Skill(
//            name = "Haunt",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Movement","Attack","Defense","Support"),
//            traits = listOf("Spirit Medium"),
//            description = "On your first turn you start at 0 hp, once per battle, your spirit exits your body and may take your turn as if you were alive.  You cannot take damage in this form, can move through enemies and walls with any movement, and at the end of your turn your spirit returns to your body.",
//        ),
//        Skill(
//            name = "Snap Freeze",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = true,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "You conjure an icy beam aimed at a target within 15 ft/3 hexes to freeze them solid.  If it hits, it deals 3d5 + half Magic damage and the target is Chilled for 2 turns.\n" +
//                    "Focus Mode/Cost: 3 turn cooldown\n" +
//                    "Perform the same attack as the standard skill.  If the target is hit, enemies within 5 ft/2 hexes of the target are Chilled for 1 turn.\n",
//        ),
//        Skill(
//            name = "Hellish Aura",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf("Devil Worship"),
//            description = "Any target you hit with an attack or that damages you within 5 ft/1 hex is Burned for 1 turn.",
//        ),
//        Skill(
//            name = "Sprite Spite",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = true,
//            slots = listOf("Attack"),
//            traits = listOf("Friend of the Fae"),
//            description = "You call the aid of a very irate faerie, who will deal 1d10 + half Magic damage to a target within 15 ft/3 hexes without rolling to hit.\n" +
//                    "Focus Mode/Cost: 1 Charge\n" +
//                    "Max Charges: 1\n" +
//                    "3 angry sprites answer your call, dealing 1d10 + half Magic damage to 3 targets (different or the same) within 15 ft/3 hexes without rolling to hit.\n",
//        ),
//        Skill(
//            name = "Bones of Steel",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "You mutter an ancient incantation, granting your body abnormal resistance and sturdiness.  Until the end of your next turn, damage equal to or less than your Power is negated.  Damage that isn’t negated is reduced by half Power.",
//        ),
//        Skill(
//            name = "Blood Transfusion",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Support"),
//            traits = listOf(""),
//            description = "You utilize some handy blood from a previous sacrifice to replenish some of your own, or an ally’s.  Heal yourself or an ally within 5 ft/1 hex for 4d5 health.",
//        ),
//        Skill(
//            name = "Grimoire Bash",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "You slam a meaty volume of dark doctrine into the skull of a target within 5 ft/1 hex, dealing 3d10 + Power damage if it hits.",
//        ),
//        Skill(
//            name = "Grimoire Blast",
//            set = "Calamitous Cult",
//            type = "Actie",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "You read from your book of shadow scripture to cast a blast of dark energy at a target within 15 ft/3 hexes, dealing 4d5 + Magic damage if it hits.",
//        ),
//        Skill(
//            name = "Mini Doomsday",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = true,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "You call upon the stars to deliver destruction upon your enemies.  A meteorite plummets toward a target within 30 ft/6 hexes, dealing 2d20 damage if it hits.\n" +
//                    "Focus Mode/Cost: 5 turn Cooldown\n" +
//                    "You perform the same attack as standard, dealing 1d50 damage instead of 2d20 if the attack hits.\n",
//        ),
//        Skill(
//            name = "Dryad Blessing",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Defense","Support"),
//            traits = listOf("Friend of the Fae"),
//            description = "A forest spirit surrounds you with magical, protective branches.  For up to 2 turns (may be canceled at any time), damage is reduced by your Magic, and you heal 2d10 hp at the end of your turn while this is active. You cannot move while this skill is active.",
//        ),
//        Skill(
//            name = "Dextrous Slice",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Movement","Active"),
//            traits = listOf(""),
//            description = "You flip a concealed blade out of your sleeve, and quickly slice at an enemy within 5 ft/1 hex, dealing 4d5 damage if you hit.  Whether the attack hits or not, afterward you may backflip directly 5 ft/1 hex away from the enemy you just attacked.  If that space is occupied, you may not move.  If you did move, you may make another attack on a target within 5 ft/1 hex, dealing 4d5 damage if it hits.",
//        ),
//        Skill(
//            name = "Vicious Counter",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Attack","Defense"),
//            traits = listOf(""),
//            description = "You ready a concealed weapon covered in countless micro edges. The next time you would take damage from an enemy within 5 ft/1 hex, you swiftly knock the attack aside, and slash the vulnerable target, dealing 4d5 damage if you hit, and applying a bleed equal to your Power for 2 turns.",
//        ),
//        Skill(
//            name = "One with the Darkness",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "Cost: 3 turn Cooldown\n" +
//                    "You cloak yourself in complete darkness, vanishing into the shadows.  You have the Stealth status until the end of your next turn.",
//        ),
//        Skill(
//            name = "Selective Possession",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Movement","Attack","Defense","Support"),
//            traits = listOf("Spirit Medium"),
//            description = "You absorb a piece of the spirit energy of each enemy you damage.  If the enemy you most recently damaged has an active skill in a matching slot to this skill, you may use (one of) their active skill(s) in this slot instead of your own. ",
//        ),
//        Skill(
//            name = "Abyssal Blessing",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Support"),
//            traits = listOf(""),
//            description = "On a point within 30 ft/6 hexes of you, you conjure a dark portal to your master’s lair, from which his dark energy can wash over you.  The portal counts as a small obstacle, and at the end of your turn while active, it emits a wave of healing that heals allies within 15 ft/3 hexes for 1d20 + Magic health, and deals 1d5 damage to enemies within the same area without rolling to hit.",
//        ),
//        Skill(
//            name = "Cursed Blow",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "You imbue your fist with dark magic energy, and strike at a target within 5 ft/1 hex.  If you hit, you deal 2d5 + Power + Magic damage.",
//        ),
//        Skill(
//            name = "Deal with the Devil",
//            set = "Calamitous Cult",
//            type = "Passive",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Utility"),
//            traits = listOf("Devil Worship"),
//            description = "Satan can grant many wishes, a turn of the dice being a relatively simple one, and at the low low price of a fragment of your soul.  Before knowing the result of a roll, you may change the dice to a value of your choice.  If you do so, you must lose a point in a stat of your choice other than Focus.  Stats cannot be reduced below 0, and if you cannot lose a point you cannot use this effect.",
//        ),
//        Skill(
//            name = "Tentacle Call",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Utility"),
//            traits = listOf(""),
//            description = "Utilizing a primordial ritual, you summon a ring of large flailing tentacles around yourself.  Make an attack roll against all enemies within 10 ft/2 hexes, any that are hit take 2d10 damage and are Staggered for 1 turn.",
//        ),
//        Skill(
//            name = "Rodlike Speed",
//            set = "Calamitous Cult",
//            type = "Both",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Movement"),
//            traits = listOf(""),
//            description = "Passive\n" +
//                    "Your Free Movement distance is doubled.\n" +
//                    "Active\n" +
//                    "Moving faster than the eye can comprehend, like a cryptid, your Free Movement distance is doubled again for this turn and cannot provoke opportunity attacks.\n",
//        ),
//        Skill(
//            name = "Mountain of Madness",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 5,
//            focusMode = false,
//            slots = listOf("Utility"),
//            traits = listOf(""),
//            description = "A phantom mountain of dizzying height rises around you, obscuring your figure.  All enemies within 30 ft/6 hexes are made Dizzy, and until the end of your next turn any damage you would take below or equal to 15 damage is negated.",
//        ),
//        Skill(
//            name = "Brain Rot",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 5,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf("Plague Bearer"),
//            description = "You redirect the poison afflicting a target to enter their brain.  If there is a target within 30 ft/6 hexes that has any stacks of Poison, you may deal 5d5 damage to them if you hit, and double their Poison stacks.  If there are no targets afflicted by Poison, you may choose any target and apply 2d5 Poison stacks without rolling to hit.",
//        ),
//        Skill(
//            name = "Infernal Resistance",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 5,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf("Devil Worship"),
//            description = "You call upon the protective energy of the flames of hell.  Until the end of your next turn, attacks targeting you or an ally within 30 ft/6 hexes must roll above or equal to 5/10.",
//        ),
//        Skill(
//            name = "Satyr Ale",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 5,
//            focusMode = false,
//            slots = listOf("Support"),
//            traits = listOf("Friend of the Fae"),
//            description = "A jovial goatman fae appears before you, bearing 5 servings of hearty, healing drink.  Each serving heals 2d5 + Magic health, and can be distributed however you wish between yourself and allies within 30 ft/6 hexes.",
//        ),
//        Skill(
//            name = "Shiverwalk",
//            set = "Calamitous Cult",
//            type = "Active",
//            level = 5,
//            focusMode = false,
//            slots = listOf("Movement"),
//            traits = listOf("Spirit Medium"),
//            description = "You fade completely into spirit form, and drift throughout the battlefield causing chills to any you touch.  You may move 20 ft/4 hexes plus your Free Movement distance.  During this time, you do not trigger Opportunity Attacks, you may move through enemies.  Enemies you move through take 1d10 damage without rolling to hit, and are Chilled for 1 turn.",
//        ),
//        Skill(
//            name = "Combo Booster",
//            set = "Standard",
//            type = "Passive",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Movement","Attack","Defense","Support"),
//            traits = listOf(""),
//            description = "If this is the third skill used on your turn, you may gain an additional action.",
//        ),
//        Skill(
//            name = "Stronger Shield",
//            set = "Standard",
//            type = "Passive",
//            level = 2,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "Any damage negation threshold effects applied to you are increased by half of your Power.",
//        ),
//        Skill(
//            name = "Midas Touch",
//            set = "Standard",
//            type = "Passive",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "When you make an attack that kills an enemy, you gain (1d5 - 2) * 10 currency.",
//        ),
//        Skill(
//            name = "Good Karma",
//            set = "Standard",
//            type = "Passive",
//            level = 3,
//            focusMode = false,
//            slots = listOf("Support"),
//            traits = listOf(""),
//            description = "When you use an active Support action on your turn, you heal for 2d5 health.",
//        ),
//        Skill(
//            name = "Mythic Artifact",
//            set = "Standard",
//            type = "Passive",
//            level = 4,
//            focusMode = false,
//            slots = listOf("Movement","Attack","Defense","Support"),
//            traits = listOf(""),
//            description = "While this skill is equipped, +1 to all your stats.",
//        ),
//        Skill(
//            name = "Upgrade Up",
//            set = "Standard",
//            type = "Passive",
//            level = 5,
//            focusMode = false,
//            slots = listOf("Movement","Attack","Defense","Support"),
//            traits = listOf(""),
//            description = "The active skill in this slot may have 1 additional upgrade equipped.",
//        ),
//        Skill(
//            name = "Basic Sprint",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Movement"),
//            traits = listOf(""),
//            description = "This enemy sprints up to an additional 5ft / 1 hex for each Speed point.",
//        ),
//        Skill(
//            name = "Basic Roll",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Movement"),
//            traits = listOf(""),
//            description = "This enemy somersaults up to 15 ft / 3 hexes, avoiding opportunity attacks provoked by this movement.",
//        ),
//        Skill(
//            name = "Basic Melee",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "This enemy swings with an appendage toward a target within 5ft/1 hex, dealing this enemy’s Power in damage.",
//        ),
//        Skill(
//            name = "Basic Ranged",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "This enemy lobs a projectile or rock toward a target within 30 ft / 6 hexes.  If the target is 5 ft/1 hex away, the attack gets -1 to hit.  If the attack hits, it deals 1d5 + half Power damage.",
//        ),
//        Skill(
//            name = "Basic Magic",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Attack"),
//            traits = listOf(""),
//            description = "This enemy casts a magical projectile at a target within 30 ft / 6 hexes.  If the attack hits, it deals 1d5 + half Magic damage.",
//        ),
//        Skill(
//            name = "Basic Block",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "This enemy raises their guard to lessen the effect of incoming blows.  Incoming damage is reduced by half of their Vigor mod until the end of their next turn.",
//        ),
//        Skill(
//            name = "Basic Dodge",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "This enemy becomes increasingly prepared to dodge incoming attacks.  Rolls to hit them must be 2 + (current floor number) / 10 in order to hit for 2 turns.  This effect cannot stack but can be used again to refresh the duration.",
//        ),
//        Skill(
//            name = "Basic Shield",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Defense"),
//            traits = listOf(""),
//            description = "This enemy raises a piece of debris or armor to block incoming attacks.  Damage less than half of their vigor mod + (current floor number) is negated until the end of their next turn.",
//        ),
//        Skill(
//            name = "Basic First Aid",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Support"),
//            traits = listOf(""),
//            description = "This enemy treats the wounds of an ally, restoring (current floor number)d5 health to an ally within 5 ft / 1 hex.",
//        ),
//        Skill(
//            name = "Basic Tag Team",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Support"),
//            traits = listOf(""),
//            description = "This enemy aims to assist an ally on a future attack.  An enemy within 15 ft / 3 hexes gains +1 to hit and + (1d5 + Power) on their next attack.",
//        ),
//        Skill(
//            name = "Basic Condition Spread",
//            set = "Standard",
//            type = "Enemy",
//            level = 0,
//            focusMode = false,
//            slots = listOf("Utility"),
//            traits = listOf(""),
//            description = "This enemy abuses a previous technique or existing condition to worsen or spread a status effect.  They may choose any target within 45 ft / 9 hexes with a status condition, and they may either copy the status onto another target with no status effects within 45 ft / 9 hexes, double the stacks, or double the duration on the target.",
//        ),
    )
}